/**
 * @file drivers/stepper/adi_tmc/adi_tmc_reg.h
 *
 * @brief TMC Registers
 *
 */

/*
 * SPDX-FileCopyrightText: Copyright (c) 2024 Carl Zeiss Meditec AG
 * SPDX-FileCopyrightText: Copyright (c) 2025 Prevas A/S
 * SPDX-FileCopyrightText: Copyright (c) 2026 A. Schweigstill
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_DRIVERS_STEPPER_ADI_TMC_COMMON_ADI_TMC_REG_H_
#define ZEPHYR_DRIVERS_STEPPER_ADI_TMC_COMMON_ADI_TMC_REG_H_

#ifdef __cplusplus
extern "C" {
#endif

/** Common Registers for TMC50XX, TMC51XX and TMC524X */
#if defined(CONFIG_STEPPER_ADI_TMC50XX) || defined(CONFIG_STEPPER_ADI_TMC51XX) || defined(CONFIG_STEPPER_ADI_TMC524X)

#define TMC5XXX_WRITE_BIT        0x80U
#define TMC5XXX_ADDRESS_MASK     0x7FU

#define TMC5XXX_GCONF 0x00
#define TMC5XXX_GSTAT 0x01

#endif

/** Common Registers for TMC50XX and TMC51XX */
#if defined(CONFIG_STEPPER_ADI_TMC50XX) || defined(CONFIG_STEPPER_ADI_TMC51XX)

#define TMC5XXX_CLOCK_FREQ_SHIFT 24

#define TMC5XXX_RAMPMODE_POSITIONING_MODE       0
#define TMC5XXX_RAMPMODE_POSITIVE_VELOCITY_MODE 1
#define TMC5XXX_RAMPMODE_NEGATIVE_VELOCITY_MODE 2
#define TMC5XXX_RAMPMODE_HOLD_MODE              3

#define TMC5XXX_SG_MIN_VALUE -64
#define TMC5XXX_SG_MAX_VALUE 63
#define TMC5XXX_SW_MODE_SG_STOP_ENABLE BIT(10)

#define TMC5XXX_COOLCONF_SG2_THRESHOLD_VALUE_SHIFT 16

#define TMC5XXX_IHOLD_MASK  GENMASK(4, 0)
#define TMC5XXX_IHOLD_SHIFT 0
#define TMC5XXX_IHOLD(n)    (((n) << TMC5XXX_IHOLD_SHIFT) & TMC5XXX_IHOLD_MASK)

#define TMC5XXX_IRUN_MASK  GENMASK(12, 8)
#define TMC5XXX_IRUN_SHIFT 8
#define TMC5XXX_IRUN(n)    (((n) << TMC5XXX_IRUN_SHIFT) & TMC5XXX_IRUN_MASK)

#define TMC5XXX_IHOLDDELAY_MASK  GENMASK(19, 16)
#define TMC5XXX_IHOLDDELAY_SHIFT 16
#define TMC5XXX_IHOLDDELAY(n)    (((n) << TMC5XXX_IHOLDDELAY_SHIFT) & TMC5XXX_IHOLDDELAY_MASK)

#define TMC5XXX_CHOPCONF_DRV_ENABLE_MASK GENMASK(3, 0)
#define TMC5XXX_CHOPCONF_MRES_MASK       GENMASK(27, 24)
#define TMC5XXX_CHOPCONF_MRES_SHIFT      24

#define TMC5XXX_RAMPSTAT_INT_MASK  GENMASK(9, 4)
#define TMC5XXX_RAMPSTAT_INT_SHIFT 4

#define TMC5XXX_RAMPSTAT_POS_REACHED_MASK BIT(9)
#define TMC5XXX_POS_REACHED									   \
	(TMC5XXX_RAMPSTAT_POS_REACHED_MASK >> TMC5XXX_RAMPSTAT_INT_SHIFT)

#define TMC5XXX_RAMPSTAT_POS_REACHED_EVENT_MASK BIT(7)
#define TMC5XXX_POS_REACHED_EVENT                                                                  \
	(TMC5XXX_RAMPSTAT_POS_REACHED_EVENT_MASK >> TMC5XXX_RAMPSTAT_INT_SHIFT)

#define TMC5XXX_POS_REACHED_AND_EVENT (TMC5XXX_POS_REACHED | TMC5XXX_POS_REACHED_EVENT)

#define TMC5XXX_RAMPSTAT_STOP_SG_EVENT_MASK BIT(6)
#define TMC5XXX_STOP_SG_EVENT                                                                      \
	(TMC5XXX_RAMPSTAT_STOP_SG_EVENT_MASK >> TMC5XXX_RAMPSTAT_INT_SHIFT)

#define TMC5XXX_RAMPSTAT_STOP_RIGHT_EVENT_MASK BIT(5)
#define TMC5XXX_STOP_RIGHT_EVENT                                                                   \
	(TMC5XXX_RAMPSTAT_STOP_RIGHT_EVENT_MASK >> TMC5XXX_RAMPSTAT_INT_SHIFT)

#define TMC5XXX_RAMPSTAT_STOP_LEFT_EVENT_MASK BIT(4)
#define TMC5XXX_STOP_LEFT_EVENT                                                                    \
	(TMC5XXX_RAMPSTAT_STOP_LEFT_EVENT_MASK >> TMC5XXX_RAMPSTAT_INT_SHIFT)

#define TMC5XXX_DRV_STATUS_STST_BIT        BIT(31)
#define TMC5XXX_DRV_STATUS_SG_RESULT_MASK  GENMASK(9, 0)
#define TMC5XXX_DRV_STATUS_SG_STATUS_MASK  BIT(24)
#define TMC5XXX_DRV_STATUS_SG_STATUS_SHIFT 24

#define TMC50XX_MOTOR_ADDR(m)     (0x20 << (m))
#define TMC50XX_MOTOR_ADDR_DRV(m) ((m) << 4)

#define TMC50XX_RAMPMODE(motor)   (0x00 | TMC50XX_MOTOR_ADDR(motor))
#define TMC50XX_XACTUAL(motor)    (0x01 | TMC50XX_MOTOR_ADDR(motor))
#define TMC50XX_VACTUAL(motor)    (0x02 | TMC50XX_MOTOR_ADDR(motor))
#define TMC50XX_VSTART(motor)     (0x03 | TMC50XX_MOTOR_ADDR(motor))
#define TMC50XX_A1(motor)         (0x04 | TMC50XX_MOTOR_ADDR(motor))
#define TMC50XX_V1(motor)         (0x05 | TMC50XX_MOTOR_ADDR(motor))
#define TMC50XX_AMAX(motor)       (0x06 | TMC50XX_MOTOR_ADDR(motor))
#define TMC50XX_VMAX(motor)       (0x07 | TMC50XX_MOTOR_ADDR(motor))
#define TMC50XX_DMAX(motor)       (0x08 | TMC50XX_MOTOR_ADDR(motor))
#define TMC50XX_D1(motor)         (0x0A | TMC50XX_MOTOR_ADDR(motor))
#define TMC50XX_VSTOP(motor)      (0x0B | TMC50XX_MOTOR_ADDR(motor))
#define TMC50XX_TZEROWAIT(motor)  (0x0C | TMC50XX_MOTOR_ADDR(motor))
#define TMC50XX_XTARGET(motor)    (0x0D | TMC50XX_MOTOR_ADDR(motor))
#define TMC50XX_SWMODE(motor)     (0x14 | TMC50XX_MOTOR_ADDR(motor))
#define TMC50XX_RAMPSTAT(motor)   (0x15 | TMC50XX_MOTOR_ADDR(motor))
#define TMC50XX_CHOPCONF(motor)   (0x6C | TMC50XX_MOTOR_ADDR_DRV(motor))
#define TMC50XX_COOLCONF(motor)   (0x6D | TMC50XX_MOTOR_ADDR_DRV(motor))
#define TMC50XX_DRVSTATUS(motor)  (0x6F | TMC50XX_MOTOR_ADDR_DRV(motor))

#endif

#ifdef CONFIG_STEPPER_ADI_TMC50XX

#define TMC50XX_MOTOR_ADDR_PWM(m) ((m) << 3)

/**
 * @name TMC50XX module registers
 * @anchor TMC50XX_REGISTERS
 *
 * @{
 */

#define TMC50XX_GCONF_POSCMP_ENABLE_SHIFT 3
#define TMC50XX_GCONF_TEST_MODE_SHIFT     7
#define TMC50XX_GCONF_SHAFT_SHIFT(n)      ((n) ? 8 : 9)
#define TMC50XX_LOCK_GCONF_SHIFT          10

#define TMC50XX_PWMCONF(motor)    (0x10 | TMC50XX_MOTOR_ADDR_PWM(motor))
#define TMC50XX_PWM_STATUS(motor) (0x11 | TMC50XX_MOTOR_ADDR_PWM(motor))

#define TMC50XX_IHOLD_IRUN(motor) (0x10 | TMC50XX_MOTOR_ADDR(motor))
#define TMC50XX_VCOOLTHRS(motor)  (0x11 | TMC50XX_MOTOR_ADDR(motor))
#define TMC50XX_VHIGH(motor)      (0x12 | TMC50XX_MOTOR_ADDR(motor))
#define TMC50XX_XLATCH(motor)     (0x16 | TMC50XX_MOTOR_ADDR(motor))

#define TMC50XX_MSLUT0(motor)     (0x60 | TMC50XX_MOTOR_ADDR_DRV(motor))
#define TMC50XX_MSLUT1(motor)     (0x61 | TMC50XX_MOTOR_ADDR_DRV(motor))
#define TMC50XX_MSLUT2(motor)     (0x62 | TMC50XX_MOTOR_ADDR_DRV(motor))
#define TMC50XX_MSLUT3(motor)     (0x63 | TMC50XX_MOTOR_ADDR_DRV(motor))
#define TMC50XX_MSLUT4(motor)     (0x64 | TMC50XX_MOTOR_ADDR_DRV(motor))
#define TMC50XX_MSLUT5(motor)     (0x65 | TMC50XX_MOTOR_ADDR_DRV(motor))
#define TMC50XX_MSLUT6(motor)     (0x66 | TMC50XX_MOTOR_ADDR_DRV(motor))
#define TMC50XX_MSLUT7(motor)     (0x67 | TMC50XX_MOTOR_ADDR_DRV(motor))
#define TMC50XX_MSLUTSEL(motor)   (0x68 | TMC50XX_MOTOR_ADDR_DRV(motor))
#define TMC50XX_MSLUTSTART(motor) (0x69 | TMC50XX_MOTOR_ADDR_DRV(motor))
#define TMC50XX_MSCNT(motor)      (0x6A | TMC50XX_MOTOR_ADDR_DRV(motor))
#define TMC50XX_MSCURACT(motor)   (0x6B | TMC50XX_MOTOR_ADDR_DRV(motor))

#endif /* CONFIG_STEPPER_ADI_TMC50XX */

#ifdef CONFIG_STEPPER_ADI_TMC51XX

#define TMC51XX_GCONF_EN_PWM_MODE_SHIFT        2
#define TMC51XX_GCONF_SHAFT_SHIFT              4
#define TMC51XX_GCONF_DIAG0_INT_PUSHPULL_SHIFT 12
#define TMC51XX_GCONF_TEST_MODE_SHIFT          17

#define TMC51XX_IHOLD_IRUN	0x10
#define TMC51XX_TPOWER_DOWN	0x11
#define TMC51XX_TSTEP		0x12
#define TMC51XX_TPWMTHRS	0x13
#define TMC51XX_TCOOLTHRS	0x14
#define TMC51XX_THIGH		0x15

#define TMC51XX_RAMPMODE	TMC50XX_RAMPMODE(0)
#define TMC51XX_XACTUAL		TMC50XX_XACTUAL(0)
#define TMC51XX_VACTUAL		TMC50XX_VACTUAL(0)
#define TMC51XX_VSTART		TMC50XX_VSTART(0)
#define TMC51XX_A1		TMC50XX_A1(0)
#define TMC51XX_V1		TMC50XX_V1(0)
#define TMC51XX_AMAX		TMC50XX_AMAX(0)
#define TMC51XX_VMAX		TMC50XX_VMAX(0)
#define TMC51XX_DMAX		TMC50XX_DMAX(0)
#define TMC51XX_D1		TMC50XX_D1(0)
#define TMC51XX_VSTOP		TMC50XX_VSTOP(0)
#define TMC51XX_TZEROWAIT	TMC50XX_TZEROWAIT(0)
#define TMC51XX_XTARGET		TMC50XX_XTARGET(0)
#define TMC51XX_SWMODE		TMC50XX_SWMODE(0)
#define TMC51XX_RAMPSTAT	TMC50XX_RAMPSTAT(0)
#define TMC51XX_CHOPCONF	TMC50XX_CHOPCONF(0)
#define TMC51XX_COOLCONF	TMC50XX_COOLCONF(0)
#define TMC51XX_DRVSTATUS	TMC50XX_DRVSTATUS(0)

#endif /* CONFIG_STEPPER_ADI_TMC51XX */

#ifdef CONFIG_STEPPER_ADI_TMC524X

/* === TMC5240 (TMC524X) register addresses === */

#define TMC524X_IFCNT				0x02
#define TMC524X_NODECONF	   		0x03
#define TMC524X_IOIN 				0x04
#define TMC524X_X_COMPARE			0x05
#define TMC524X_X_COMPARE_REPEAT	0x06
#define TMC524X_DRV_CONF			0x0A
#define TMC524X_GLOBAL_SCALER		0x0B


/* Velocity dependent configuration registers */
#define TMC524X_IHOLD_IRUN          0x10
#define TMC524X_TPOWER_DOWN         0x11
#define TMC524X_TSTEP               0x12
#define TMC524X_TPWMTHRS            0x13
#define TMC524X_TCOOLTHRS           0x14
#define TMC524X_THIGH               0x15

/* Ramp generator registers */
#define TMC524X_RAMPMODE            0x20
#define TMC524X_XACTUAL             0x21
#define TMC524X_VACTUAL             0x22
#define TMC524X_VSTART              0x23
#define TMC524X_A1                  0x24
#define TMC524X_V1                  0x25
#define TMC524X_AMAX                0x26
#define TMC524X_VMAX                0x27
#define TMC524X_DMAX                0x28
#define TMC524X_TVMAX               0x29
#define TMC524X_D1                  0x2A
#define TMC524X_VSTOP               0x2B
#define TMC524X_TZEROWAIT           0x2C
#define TMC524X_XTARGET             0x2D
#define TMC524X_V2					0x2E
#define TMC524X_A2					0x2F
#define TMC524X_D2					0x30

/* Ramp / switch config + status */

#define TMC524X_VDCMIN_ADDR			0x33		/* With _ADDR suffix in order to avoid confusion with shifted value */
#define TMC524X_SWMODE              0x34
#define TMC524X_RAMPSTAT            0x35
#define TMC524X_XLATCH				0x36

/* Encoder registers */
#define TMC524X_ENCMODE				0x38
#define TMC524X_X_ENC				0x39
#define TMC524X_ENC_CONST			0x3A
#define TMC524X_ENC_STATUS			0x3B
#define TMC524X_ENC_LATCH			0x3C
#define TMC524X_ENC_DEVIATION		0x3D
#define TMC524X_VIRTUAL_STOP_L		0x3E
#define TMC524X_VIRTUAL_STOP_R		0x3F

/* ADC registers */

#define TMC524X_ADC_VSUPPLY_AIN		0x50
#define TMC524X_ADC_TEMP			0x51
#define TMC524X_OTW_OV_VTH			0x52

/* Motor driver registers */
#define TMC524X_MSLUT0				0x60
#define TMC524X_MSLUT1				0x61
#define TMC524X_MSLUT2				0x62
#define TMC524X_MSLUT3				0x63
#define TMC524X_MSLUT4				0x64
#define TMC524X_MSLUT5				0x65
#define TMC524X_MSLUT6				0x66
#define TMC524X_MSLUT7				0x67
#define TMC524X_MSLUTSEL			0x68
#define TMC524X_MSLUTSTART			0x69
#define TMC524X_MSCNT				0x6A
#define TMC524X_MSCURACT			0x6B
#define TMC524X_CHOPCONF			0x6C
#define TMC524X_COOLCONF			0x6D
#define TMC524X_DCCTRL				0x6E
#define TMC524X_DRVSTATUS           0x6F

#define TMC524X_PWMCONF				0x70
#define TMC524X_PWM_SCALE     		0x71
#define TMC524X_PWM_AUTO      		0x72
#define TMC524X_SG4_THRS      		0x74
#define TMC524X_SG4_RESULT    		0x75
#define TMC524X_IND                 0x76

/* === GCONF bit positions (TMC5240) === */
#define TMC524X_GCONF_FAST_STANDSTILL			BIT(1)
#define TMC524X_GCONF_EN_PWM_MODE				BIT(2)
#define TMC524X_GCONF_SHAFT						BIT(4)
#define TMC524X_GCONF_DIAG0_NINT_STEP			BIT(7)
#define TMC524X_GCONF_DIAG1_NPOSCOMP_DIR		BIT(8)
#define TMC524X_GCONF_DIAG0_INT_PUSHPULL		BIT(12)
#define TMC524X_GCONF_DIAG1_POSCOMP_PUSHPULL	BIT(13)
#define TMC524X_GCONF_SMALL_HYSTERESIS			BIT(14)
#define TMC524X_GCONF_STOP_ENABLE				BIT(15)
#define TMC524X_GCONF_DIRECT_MODE				BIT(16)
/* length_step_pulse is a 4-bit field at bits [20:17] */
#define TMC524X_GCONF_LENGTH_STEP_PULSE_SHIFT	17
#define TMC524X_GCONF_LENGTH_STEP_PULSE_MASK	GENMASK(20, 17)
#define TMC524X_GCONF_LENGTH_STEP_PULSE(n)		(((n) << TMC524X_GCONF_LENGTH_STEP_PULSE_SHIFT) & TMC524X_GCONF_LENGTH_STEP_PULSE_MASK)

/* === GSTAT bit positions (TMC5240) === */

#define TMC524X_GSTAT_RESET						BIT(0)
#define TMC524X_GSTAT_DRV_ERR					BIT(1)
#define TMC524X_GSTAT_UV_CP						BIT(2)
#define TMC524X_GSTAT_REGISTER_RESET			BIT(3)
#define TMC524X_GSTAT_VM_UVLO					BIT(4)

/* === NODECONF bit positions (TMC5240) === */

#define TMC524X_NODECONF_NODEADDR_SHIFT			0
#define TMC524X_NODECONF_NODEADDR_MASK			GENMASK(7, 0)
#define TMC524X_NODECONF_NODEADDR(n)			(((n) << TMC524X_NODECONF_NODEADDR_SHIFT) & TMC524X_NODECONF_NODEADDR_MASK)
#define TMC524X_NODECONF_SENDDELAY_SHIFT		8
#define TMC524X_NODECONF_SENDDELAY_MASK			GENMASK(11, 8)
#define TMC524X_NODECONF_SENDDELAY(n)			(((n) << TMC524X_NODECONF_SENDDELAY_SHIFT) & TMC524X_NODECONF_SENDDELAY_MASK)

/* === IOIN bit positions (TMC5240) === */

#define TMC524X_IOIN_REFL						BIT(0)
#define TMC524X_IOIN_REFR						BIT(1)
#define TMC524X_IOIN_ENCB						BIT(2)
#define TMC524X_IOIN_ENCA						BIT(3)
#define TMC524X_IOIN_DRV_ENN					BIT(4)
#define TMC524X_IOIN_ENCN						BIT(5)
#define TMC524X_IOIN_UART_EN					BIT(6)
#define TMC524X_IOIN_COMP_A						BIT(8)
#define TMC524X_IOIN_COMP_B						BIT(9)
#define TMC524X_IOIN_COMP_A1_A2					BIT(10)
#define TMC524X_IOIN_COMP_B1_B2					BIT(11)
#define TMC524X_IOIN_OUTPUT						BIT(12)
#define TMC524X_IOIN_EXT_RES_DET				BIT(13)
#define TMC524X_IOIN_EXT_CLK					BIT(14)
#define TMC524X_IOIN_ADC_ERR					BIT(15)
#define TMC524X_IOIN_SILICON_RV_SHIFT			16
#define TMC524X_IOIN_SILICON_RV_MASK			GENMASK(18, 16)
#define TMC524X_IOIN_SILICON_RV(n)				(((n) << TMC524X_IOIN_SILICON_RV_SHIFT) & TMC524X_IOIN_SILICON_RV_MASK)

/* === DRV_CONF bit positions (TMC5240) === */

#define TMC524X_DRV_CONF_CURRENT_RANGE_SHIFT	0
#define TMC524X_DRV_CONF_CURRENT_RANGE_MASK		GENMASK(1, 0)
#define TMC524X_DRV_CONF_CURRENT_RANGE(n)		(((n) << TMC524X_DRV_CONF_CURRENT_RANGE_SHIFT) & TMC524X_DRV_CONF_CURRENT_RANGE_MASK)
#define TMC524X_DRV_CONF_SLOPE_CONTROL_SHIFT	4
#define TMC524X_DRV_CONF_SLOPE_CONTROL_MASK		GENMASK(5, 4)
#define TMC524X_DRV_CONF_SLOPE_CONTROL(n)		(((n) << TMC524X_DRV_CONF_SLOPE_CONTROL_SHIFT) & TMC524X_DRV_CONF_SLOPE_CONTROL_MASK)

/* === IHOLD_IRUN bit positions (TMC5240) === */

#define TMC524X_IHOLD_MASK  					GENMASK(4, 0)
#define TMC524X_IHOLD_SHIFT 					0
#define TMC524X_IHOLD(n)    					(((n) << TMC524X_IHOLD_SHIFT) & TMC524X_IHOLD_MASK)

#define TMC524X_IRUN_MASK  						GENMASK(12, 8)
#define TMC524X_IRUN_SHIFT 						8
#define TMC524X_IRUN(n)    						(((n) << TMC524X_IRUN_SHIFT) & TMC524X_IRUN_MASK)

#define TMC524X_IHOLDDELAY_MASK  				GENMASK(19, 16)
#define TMC524X_IHOLDDELAY_SHIFT 				16
#define TMC524X_IHOLDDELAY(n)    				(((n) << TMC524X_IHOLDDELAY_SHIFT) & TMC524X_IHOLDDELAY_MASK)

#define TMC524X_IRUNDELAY_MASK  				GENMASK(27, 24)
#define TMC524X_IRUNDELAY_SHIFT 				24
#define TMC524X_IRUNDELAY(n)    				(((n) << TMC524X_IRUNDELAY_SHIFT) & TMC524X_IRUNDELAY_MASK)

/* === VDCMIN bit positions (TMC5240) === */

#define TMC524X_VDCMIN_MASK  					GENMASK(22, 8)
#define TMC524X_VDCMIN_SHIFT 					8
#define TMC524X_VDCMIN(n)    					(((n) << TMC524X_VDCMIN_SHIFT) & TMC524X_VDCMIN_MASK)

/* === SWMODE bit positions (TMC5240) === */

#define TMC524X_SWMODE_STOP_L_ENABLE			BIT(0)
#define TMC524X_SWMODE_STOP_R_ENABLE			BIT(1)
#define TMC524X_SWMODE_POL_STOP_L				BIT(2)
#define TMC524X_SWMODE_POL_STOP_R				BIT(3)
#define TMC524X_SWMODE_SWAP_LR					BIT(4)
#define TMC524X_SWMODE_LATCH_L_ACTIVE			BIT(5)
#define TMC524X_SWMODE_LATCH_L_INACTIVE			BIT(6)
#define TMC524X_SWMODE_LATCH_R_ACTIVE			BIT(7)
#define TMC524X_SWMODE_LATCH_R_INACTIVE			BIT(8)
#define TMC524X_SWMODE_EN_LATCH_ENCODER			BIT(9)
#define TMC524X_SWMODE_SG_STOP					BIT(10)
#define TMC524X_SWMODE_EN_SOFTSTOP				BIT(11)
#define TMC524X_SWMODE_EN_VIRTUAL_STOP_L		BIT(12)
#define TMC524X_SWMODE_EN_VIRTUAL_STOP_R		BIT(13)
#define TMC524X_SWMODE_VIRTUAL_STOP_ENC			BIT(14)

/* === RAMPSTAT bit positions (TMC5240) === */

#define TMC524X_RAMPSTAT_STATUS_STOP_L			BIT(0)
#define TMC524X_RAMPSTAT_STATUS_STOP_R			BIT(1)
#define TMC524X_RAMPSTAT_STATUS_LATCH_L			BIT(2)
#define TMC524X_RAMPSTAT_STATUS_LATCH_R			BIT(3)
#define TMC524X_RAMPSTAT_EVENT_STOP_L			BIT(4)
#define TMC524X_RAMPSTAT_EVENT_STOP_R			BIT(5)
#define TMC524X_RAMPSTAT_EVENT_STOP_SG			BIT(6)
#define TMC524X_RAMPSTAT_EVENT_POS_REACHED		BIT(7)
#define TMC524X_RAMPSTAT_VELOCITY_REACHED		BIT(8)
#define TMC524X_RAMPSTAT_POSITION_REACHED		BIT(9)
#define TMC524X_RAMPSTAT_VZERO					BIT(10)
#define TMC524X_RAMPSTAT_T_ZEROWAIT_ACTIVE		BIT(11)
#define TMC524X_RAMPSTAT_SECOND_MOVE			BIT(12)
#define TMC524X_RAMPSTAT_STATUS_SG				BIT(13)
#define TMC524X_RAMPSTAT_STATUS_VIRTUAL_STOP_L	BIT(14)
#define TMC524X_RAMPSTAT_STATUS_VIRTUAL_STOP_R	BIT(15)

/* === ENCMODE bit positions (TMC5240) === */

#define TMC524X_ENCMODE_POL_A                   BIT(0)
#define TMC524X_ENCMODE_POL_B                   BIT(1)
#define TMC524X_ENCMODE_POL_N                   BIT(2)
#define TMC524X_ENCMODE_IGNORE_AB               BIT(3)
#define TMC524X_ENCMODE_CLR_CONT                BIT(4)
#define TMC524X_ENCMODE_CLR_ONCE                BIT(5)
#define TMC524X_ENCMODE_POS_NEG_EDGE_MASK  		GENMASK(7, 6)
#define TMC524X_ENCMODE_POS_NEG_EDGE_SHIFT 		6
#define TMC524X_ENCMODE_POS_NEG_EDGE(n)    		(((n) << TMC524X_ENCMODE_POS_NEG_EDGE_SHIFT) & TMC524X_ENCMODE_POS_NEG_EDGE_MASK)
#define TMC524X_ENCMODE_CLR_ENC_X               BIT(8)
#define TMC524X_ENCMODE_LATCH_X_ACT             BIT(9)
#define TMC524X_ENCMODE_ENC_SEL_DECIMAL         BIT(10)

/* === ENCMODE bit positions (TMC5240) === */

#define TMC524X_ENCSTATUS_N_EVENT				BIT(0)
#define TMC524X_ENCSTATUS_DEVIATION_WARN		BIT(1)

/* === ADC_VSUPPLY_AIN bit positions (TMC5240) === */

#define TMC524X_ADC_VSUPPLY_MASK				GENMASK(12, 0)
#define TMC524X_ADC_VSUPPLY_SHIFT				0
#define TMC524X_ADC_VSUPPLY(n)					(((n) << TMC524X_ADC_VSUPPLY_SHIFT) & TMC524X_ADC_VSUPPLY_MASK)
#define TMC524X_ADC_VIN_MASK					GENMASK(28, 16)
#define TMC524X_ADC_VIN_SHIFT					16
#define TMC524X_ADC_VIN(n)						(((n) << TMC524X_ADC_VIN_SHIFT) & TMC524X_ADC_VIN_MASK)
                       
/* === OTW_OV_VTH bit positions (TMC5240) === */

#define TMC524X_OTW_OV_VTH_MASK					GENMASK(12, 0)
#define TMC524X_OTW_OV_VTH_SHIFT                0
#define TMC524X_OTW_OV_VTH(n)                   (((n) << TMC524X_OTW_OV_VTH_SHIFT) & TMC524X_OTW_OV_VTH_MASK)
#define TMC524X_OVERTEMMPPREWARNING_VTH_MASK    GENMASK(28, 16)
#define TMC524X_OVERTEMMPPREWARNING_VTH_SHIFT   16
#define TMC524X_OVERTEMMPPREWARNING_VTH(n)      (((n) << TMC524X_OVERTEMMPPREWARNING_VTH_SHIFT) & TMC524X_OVERTEMMPPREWARNING_VTH_MASK)

/* === TMC524X_MSLUTSEL bit positions (TMC5240) === */

#define TMC524X_MSLUTSEL_W0_MASK 				GENMASK(1, 0)
#define TMC524X_MSLUTSEL_W0_SHIFT				0
#define TMC524X_MSLUTSEL_W0(n)					(((n) << TMC524X_MSLUTSEL_W0_SHIFT) & TMC524X_MSLUTSEL_W0_MASK)
#define TMC524X_MSLUTSEL_W1_MASK 				GENMASK(3, 2)
#define TMC524X_MSLUTSEL_W1_SHIFT   			2
#define TMC524X_MSLUTSEL_W1(n)					(((n) << TMC524X_MSLUTSEL_W1_SHIFT) & TMC524X_MSLUTSEL_W1_MASK)
#define TMC524X_MSLUTSEL_W2_MASK 				GENMASK(5, 4)
#define TMC524X_MSLUTSEL_W2_SHIFT   			4
#define TMC524X_MSLUTSEL_W2(n)					(((n) << TMC524X_MSLUTSEL_W2_SHIFT) & TMC524X_MSLUTSEL_W2_MASK)
#define TMC524X_MSLUTSEL_W3_MASK 				GENMASK(7, 6)
#define TMC524X_MSLUTSEL_W3_SHIFT   			6
#define TMC524X_MSLUTSEL_W3(n)					(((n) << TMC524X_MSLUTSEL_W3_SHIFT) & TMC524X_MSLUTSEL_W3_MASK)
#define TMC524X_MSLUTSEL_X1_MASK 				GENMASK(15, 8)
#define TMC524X_MSLUTSEL_X1_SHIFT   			8
#define TMC524X_MSLUTSEL_X1(n)					(((n) << TMC524X_MSLUTSEL_X1_SHIFT) & TMC524X_MSLUTSEL_X1_MASK)
#define TMC524X_MSLUTSEL_X2_MASK 				GENMASK(23, 16)
#define TMC524X_MSLUTSEL_X2_SHIFT   			16
#define TMC524X_MSLUTSEL_X2(n)					(((n) << TMC524X_MSLUTSEL_X2_SHIFT) & TMC524X_MSLUTSEL_X2_MASK)
#define TMC524X_MSLUTSEL_X3_MASK 				GENMASK(31, 24)
#define TMC524X_MSLUTSEL_X3_SHIFT   			24
#define TMC524X_MSLUTSEL_X3(n)					(((n) << TMC524X_MSLUTSEL_X3_SHIFT) & TMC524X_MSLUTSEL_X3_MASK)

/* === TMC524X_MSLUTSTART bit positions (TMC5240) === */

#define TMC524X_MSLUTSTART_START_SIN_MASK		GENMASK(7, 0)
#define TMC524X_MSLUTSTART_START_SIN_SHIFT		0
#define TMC524X_MSLUTSTART_START_SIN(n)			(((n) << TMC524X_MSLUTSTART_START_SIN_SHIFT) & TMC524X_MSLUTSTART_START_SIN_MASK)
#define TMC524X_MSLUTSTART_START_SIN90_MASK		GENMASK(23, 16)
#define TMC524X_MSLUTSTART_START_SIN90_SHIFT	16
#define TMC524X_MSLUTSTART_START_SIN90(n)		(((n) << TMC524X_MSLUTSTART_START_SIN90_SHIFT) & TMC524X_MSLUTSTART_START_SIN90_MASK)
#define TMC524X_MSLUTSTART_OFFSET_SIN90_MASK	GENMASK(31, 24)
#define TMC524X_MSLUTSTART_OFFSET_SIN90_SHIFT	24
#define TMC524X_MSLUTSTART_OFFSET_SIN90(n)		(((n) << TMC524X_MSLUTSTART_OFFSET_SIN90_SHIFT) & TMC524X_MSLUTSTART_OFFSET_SIN90_MASK)


#define TMC524X_MSCURACT_CUR_B_MASK 			GENMASK(8, 0)
#define TMC524X_MSCURACT_CUR_B_SHIFT			0
#define TMC524X_MSCURACT_CUR_B(n)				(((n) << TMC524X_MSCURACT_CUR_B_SHIFT) & TMC524X_MSCURACT_CUR_B_MASK)
#define TMC524X_MSCURACT_CUR_A_MASK				GENMASK(24, 16)
#define TMC524X_MSCURACT_CUR_A_SHIFT			16
#define TMC524X_MSCURACT_CUR_A(n)				(((n) << TMC524X_MSCURACT_CUR_A_SHIFT) & TMC524X_MSCURACT_CUR_A_MASK)


                       
#if 0
#define TMC524X__MASK GENMASK(3, 0)
#define TMC524X__SHIFT      24
#define TMC524X_(n)    		(((n) << ) & )
#endif




#define TMC524X_CHOPCONF_DRV_ENABLE_MASK GENMASK(3, 0)
#define TMC524X_CHOPCONF_MRES_MASK       GENMASK(27, 24)
#define TMC524X_CHOPCONF_MRES_SHIFT      24

#define TMC524X_RAMPSTAT_INT_MASK  GENMASK(9, 4)
#define TMC524X_RAMPSTAT_INT_SHIFT 4




// (((n) << _SHIFT) & _MASK)

#endif /* CONFIG_STEPPER_ADI_TMC524X */

/**
 * @}
 */

#ifdef __cplusplus
}
#endif

#endif /* ZEPHYR_DRIVERS_STEPPER_ADI_TMC_COMMON_ADI_TMC_REG_H_ */
