/**
 * @file drivers/stepper/adi_tmc/adi_tmc_reg.h
 *
 * @brief TMC Registers
 *
 */

/*
 * SPDX-FileCopyrightText: Copyright (c) 2024 Carl Zeiss Meditec AG
 * SPDX-FileCopyrightText: Copyright (c) 2025 Prevas A/S
 * SPDX-FileCopyrightText: Copyright (c) 2026 A. Schweigstill
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_DRIVERS_STEPPER_ADI_TMC_COMMON_ADI_TMC_REG_H_
#define ZEPHYR_DRIVERS_STEPPER_ADI_TMC_COMMON_ADI_TMC_REG_H_

#ifdef __cplusplus
extern "C" {
#endif

/** Common Registers for TMC50XX, TMC51XX and TMC52XX */
#if defined(CONFIG_STEPPER_ADI_TMC50XX) || defined(CONFIG_STEPPER_ADI_TMC51XX) || defined(CONFIG_STEPPER_ADI_TMC52XX)

#define TMC5XXX_WRITE_BIT        0x80U
#define TMC5XXX_ADDRESS_MASK     0x7FU

#define TMC5XXX_GCONF 0x00
#define TMC5XXX_GSTAT 0x01

#endif

/** Common Registers for TMC50XX and TMC51XX */
#if defined(CONFIG_STEPPER_ADI_TMC50XX) || defined(CONFIG_STEPPER_ADI_TMC51XX)

#define TMC5XXX_CLOCK_FREQ_SHIFT 24

#define TMC5XXX_RAMPMODE_POSITIONING_MODE       0
#define TMC5XXX_RAMPMODE_POSITIVE_VELOCITY_MODE 1
#define TMC5XXX_RAMPMODE_NEGATIVE_VELOCITY_MODE 2
#define TMC5XXX_RAMPMODE_HOLD_MODE              3

#define TMC5XXX_SG_MIN_VALUE -64
#define TMC5XXX_SG_MAX_VALUE 63
#define TMC5XXX_SW_MODE_SG_STOP_ENABLE BIT(10)

#define TMC5XXX_COOLCONF_SG2_THRESHOLD_VALUE_SHIFT 16

#define TMC5XXX_IHOLD_MASK  GENMASK(4, 0)
#define TMC5XXX_IHOLD_SHIFT 0
#define TMC5XXX_IHOLD(n)    (((n) << TMC5XXX_IHOLD_SHIFT) & TMC5XXX_IHOLD_MASK)

#define TMC5XXX_IRUN_MASK  GENMASK(12, 8)
#define TMC5XXX_IRUN_SHIFT 8
#define TMC5XXX_IRUN(n)    (((n) << TMC5XXX_IRUN_SHIFT) & TMC5XXX_IRUN_MASK)

#define TMC5XXX_IHOLDDELAY_MASK  GENMASK(19, 16)
#define TMC5XXX_IHOLDDELAY_SHIFT 16
#define TMC5XXX_IHOLDDELAY(n)    (((n) << TMC5XXX_IHOLDDELAY_SHIFT) & TMC5XXX_IHOLDDELAY_MASK)

#define TMC5XXX_CHOPCONF_DRV_ENABLE_MASK GENMASK(3, 0)
#define TMC5XXX_CHOPCONF_MRES_MASK       GENMASK(27, 24)
#define TMC5XXX_CHOPCONF_MRES_SHIFT      24

#define TMC5XXX_RAMPSTAT_INT_MASK  GENMASK(9, 4)
#define TMC5XXX_RAMPSTAT_INT_SHIFT 4

#define TMC5XXX_RAMPSTAT_POS_REACHED_MASK BIT(9)
#define TMC5XXX_POS_REACHED									   \
	(TMC5XXX_RAMPSTAT_POS_REACHED_MASK >> TMC5XXX_RAMPSTAT_INT_SHIFT)

#define TMC5XXX_RAMPSTAT_POS_REACHED_EVENT_MASK BIT(7)
#define TMC5XXX_POS_REACHED_EVENT                                                                  \
	(TMC5XXX_RAMPSTAT_POS_REACHED_EVENT_MASK >> TMC5XXX_RAMPSTAT_INT_SHIFT)

#define TMC5XXX_POS_REACHED_AND_EVENT (TMC5XXX_POS_REACHED | TMC5XXX_POS_REACHED_EVENT)

#define TMC5XXX_RAMPSTAT_STOP_SG_EVENT_MASK BIT(6)
#define TMC5XXX_STOP_SG_EVENT                                                                      \
	(TMC5XXX_RAMPSTAT_STOP_SG_EVENT_MASK >> TMC5XXX_RAMPSTAT_INT_SHIFT)

#define TMC5XXX_RAMPSTAT_STOP_RIGHT_EVENT_MASK BIT(5)
#define TMC5XXX_STOP_RIGHT_EVENT                                                                   \
	(TMC5XXX_RAMPSTAT_STOP_RIGHT_EVENT_MASK >> TMC5XXX_RAMPSTAT_INT_SHIFT)

#define TMC5XXX_RAMPSTAT_STOP_LEFT_EVENT_MASK BIT(4)
#define TMC5XXX_STOP_LEFT_EVENT                                                                    \
	(TMC5XXX_RAMPSTAT_STOP_LEFT_EVENT_MASK >> TMC5XXX_RAMPSTAT_INT_SHIFT)

#define TMC5XXX_DRV_STATUS_STST_BIT        BIT(31)
#define TMC5XXX_DRV_STATUS_SG_RESULT_MASK  GENMASK(9, 0)
#define TMC5XXX_DRV_STATUS_SG_STATUS_MASK  BIT(24)
#define TMC5XXX_DRV_STATUS_SG_STATUS_SHIFT 24

#define TMC50XX_MOTOR_ADDR(m)     (0x20 << (m))
#define TMC50XX_MOTOR_ADDR_DRV(m) ((m) << 4)

#define TMC50XX_RAMPMODE(motor)   (0x00 | TMC50XX_MOTOR_ADDR(motor))
#define TMC50XX_XACTUAL(motor)    (0x01 | TMC50XX_MOTOR_ADDR(motor))
#define TMC50XX_VACTUAL(motor)    (0x02 | TMC50XX_MOTOR_ADDR(motor))
#define TMC50XX_VSTART(motor)     (0x03 | TMC50XX_MOTOR_ADDR(motor))
#define TMC50XX_A1(motor)         (0x04 | TMC50XX_MOTOR_ADDR(motor))
#define TMC50XX_V1(motor)         (0x05 | TMC50XX_MOTOR_ADDR(motor))
#define TMC50XX_AMAX(motor)       (0x06 | TMC50XX_MOTOR_ADDR(motor))
#define TMC50XX_VMAX(motor)       (0x07 | TMC50XX_MOTOR_ADDR(motor))
#define TMC50XX_DMAX(motor)       (0x08 | TMC50XX_MOTOR_ADDR(motor))
#define TMC50XX_D1(motor)         (0x0A | TMC50XX_MOTOR_ADDR(motor))
#define TMC50XX_VSTOP(motor)      (0x0B | TMC50XX_MOTOR_ADDR(motor))
#define TMC50XX_TZEROWAIT(motor)  (0x0C | TMC50XX_MOTOR_ADDR(motor))
#define TMC50XX_XTARGET(motor)    (0x0D | TMC50XX_MOTOR_ADDR(motor))
#define TMC50XX_SWMODE(motor)     (0x14 | TMC50XX_MOTOR_ADDR(motor))
#define TMC50XX_RAMPSTAT(motor)   (0x15 | TMC50XX_MOTOR_ADDR(motor))
#define TMC50XX_CHOPCONF(motor)   (0x6C | TMC50XX_MOTOR_ADDR_DRV(motor))
#define TMC50XX_COOLCONF(motor)   (0x6D | TMC50XX_MOTOR_ADDR_DRV(motor))
#define TMC50XX_DRVSTATUS(motor)  (0x6F | TMC50XX_MOTOR_ADDR_DRV(motor))

#endif

#ifdef CONFIG_STEPPER_ADI_TMC50XX

#define TMC50XX_MOTOR_ADDR_PWM(m) ((m) << 3)

/**
 * @name TMC50XX module registers
 * @anchor TMC50XX_REGISTERS
 *
 * @{
 */

#define TMC50XX_GCONF_POSCMP_ENABLE_SHIFT 3
#define TMC50XX_GCONF_TEST_MODE_SHIFT     7
#define TMC50XX_GCONF_SHAFT_SHIFT(n)      ((n) ? 8 : 9)
#define TMC50XX_LOCK_GCONF_SHIFT          10

#define TMC50XX_PWMCONF(motor)    (0x10 | TMC50XX_MOTOR_ADDR_PWM(motor))
#define TMC50XX_PWM_STATUS(motor) (0x11 | TMC50XX_MOTOR_ADDR_PWM(motor))

#define TMC50XX_IHOLD_IRUN(motor) (0x10 | TMC50XX_MOTOR_ADDR(motor))
#define TMC50XX_VCOOLTHRS(motor)  (0x11 | TMC50XX_MOTOR_ADDR(motor))
#define TMC50XX_VHIGH(motor)      (0x12 | TMC50XX_MOTOR_ADDR(motor))
#define TMC50XX_XLATCH(motor)     (0x16 | TMC50XX_MOTOR_ADDR(motor))

#define TMC50XX_MSLUT0(motor)     (0x60 | TMC50XX_MOTOR_ADDR_DRV(motor))
#define TMC50XX_MSLUT1(motor)     (0x61 | TMC50XX_MOTOR_ADDR_DRV(motor))
#define TMC50XX_MSLUT2(motor)     (0x62 | TMC50XX_MOTOR_ADDR_DRV(motor))
#define TMC50XX_MSLUT3(motor)     (0x63 | TMC50XX_MOTOR_ADDR_DRV(motor))
#define TMC50XX_MSLUT4(motor)     (0x64 | TMC50XX_MOTOR_ADDR_DRV(motor))
#define TMC50XX_MSLUT5(motor)     (0x65 | TMC50XX_MOTOR_ADDR_DRV(motor))
#define TMC50XX_MSLUT6(motor)     (0x66 | TMC50XX_MOTOR_ADDR_DRV(motor))
#define TMC50XX_MSLUT7(motor)     (0x67 | TMC50XX_MOTOR_ADDR_DRV(motor))
#define TMC50XX_MSLUTSEL(motor)   (0x68 | TMC50XX_MOTOR_ADDR_DRV(motor))
#define TMC50XX_MSLUTSTART(motor) (0x69 | TMC50XX_MOTOR_ADDR_DRV(motor))
#define TMC50XX_MSCNT(motor)      (0x6A | TMC50XX_MOTOR_ADDR_DRV(motor))
#define TMC50XX_MSCURACT(motor)   (0x6B | TMC50XX_MOTOR_ADDR_DRV(motor))

#endif /* CONFIG_STEPPER_ADI_TMC50XX */

#ifdef CONFIG_STEPPER_ADI_TMC51XX

#define TMC51XX_GCONF_EN_PWM_MODE_SHIFT        2
#define TMC51XX_GCONF_SHAFT_SHIFT              4
#define TMC51XX_GCONF_DIAG0_INT_PUSHPULL_SHIFT 12
#define TMC51XX_GCONF_TEST_MODE_SHIFT          17

#define TMC51XX_IHOLD_IRUN	0x10
#define TMC51XX_TPOWER_DOWN	0x11
#define TMC51XX_TSTEP		0x12
#define TMC51XX_TPWMTHRS	0x13
#define TMC51XX_TCOOLTHRS	0x14
#define TMC51XX_THIGH		0x15

#define TMC51XX_RAMPMODE	TMC50XX_RAMPMODE(0)
#define TMC51XX_XACTUAL		TMC50XX_XACTUAL(0)
#define TMC51XX_VACTUAL		TMC50XX_VACTUAL(0)
#define TMC51XX_VSTART		TMC50XX_VSTART(0)
#define TMC51XX_A1		TMC50XX_A1(0)
#define TMC51XX_V1		TMC50XX_V1(0)
#define TMC51XX_AMAX		TMC50XX_AMAX(0)
#define TMC51XX_VMAX		TMC50XX_VMAX(0)
#define TMC51XX_DMAX		TMC50XX_DMAX(0)
#define TMC51XX_D1		TMC50XX_D1(0)
#define TMC51XX_VSTOP		TMC50XX_VSTOP(0)
#define TMC51XX_TZEROWAIT	TMC50XX_TZEROWAIT(0)
#define TMC51XX_XTARGET		TMC50XX_XTARGET(0)
#define TMC51XX_SWMODE		TMC50XX_SWMODE(0)
#define TMC51XX_RAMPSTAT	TMC50XX_RAMPSTAT(0)
#define TMC51XX_CHOPCONF	TMC50XX_CHOPCONF(0)
#define TMC51XX_COOLCONF	TMC50XX_COOLCONF(0)
#define TMC51XX_DRVSTATUS	TMC50XX_DRVSTATUS(0)

#endif /* CONFIG_STEPPER_ADI_TMC51XX */

#ifdef CONFIG_STEPPER_ADI_TMC52XX

/* === TMC5240 (TMC52xx) register addresses === */

#define TMC52XX_IFCNT				0x02
#define TMC52XX_NODECONF	   		0x03
#define TMC52XX_IOIN 				0x04
#define TMC52XX_X_COMPARE			0x05
#define TMC52XX_X_COMPARE_REPEAT	0x06
#define TMC52XX_DRV_CONF			0x0A
#define TMC52XX_GLOBAL_SCALER		0x0B


/* Velocity dependent configuration registers */
#define TMC52XX_IHOLD_IRUN          0x10
#define TMC52XX_TPOWER_DOWN         0x11
#define TMC52XX_TSTEP               0x12
#define TMC52XX_TPWMTHRS            0x13
#define TMC52XX_TCOOLTHRS           0x14
#define TMC52XX_THIGH               0x15

/* Ramp generator registers */
#define TMC52XX_RAMPMODE            0x20
#define TMC52XX_XACTUAL             0x21
#define TMC52XX_VACTUAL             0x22
#define TMC52XX_VSTART              0x23
#define TMC52XX_A1                  0x24
#define TMC52XX_V1                  0x25
#define TMC52XX_AMAX                0x26
#define TMC52XX_VMAX                0x27
#define TMC52XX_DMAX                0x28
#define TMC52XX_TVMAX               0x29
#define TMC52XX_D1                  0x2A
#define TMC52XX_VSTOP               0x2B
#define TMC52XX_TZEROWAIT           0x2C
#define TMC52XX_XTARGET             0x2D
#define TMC52XX_V2					0x2E
#define TMC52XX_A2					0x2F
#define TMC52XX_D2					0x30

/* Ramp / switch config + status */

#define TMC52XX_VDCMIN_ADDR			0x33		/* With _ADDR suffix in order to avoid confusion with shifted value */
#define TMC52XX_SWMODE              0x34
#define TMC52XX_RAMPSTAT            0x35
#define TMC52XX_XLATCH				0x36

/* Encoder registers */
#define TMC52XX_ENCMODE				0x38
#define TMC52XX_X_ENC				0x39
#define TMC52XX_ENC_CONST			0x3A
#define TMC52XX_ENC_STATUS			0x3B
#define TMC52XX_ENC_LATCH			0x3C
#define TMC52XX_ENC_DEVIATION		0x3D
#define TMC52XX_VIRTUAL_STOP_L		0x3E
#define TMC52XX_VIRTUAL_STOP_R		0x3F

/* ADC registers */

#define TMC52XX_ADC_VSUPPLY_AIN		0x50
#define TMC52XX_ADC_TEMP			0x51
#define TMC52XX_OTW_OV_VTH			0x52

/* Motor driver registers */
#define TMC52XX_MSLUT0				0x60
#define TMC52XX_MSLUT1				0x61
#define TMC52XX_MSLUT2				0x62
#define TMC52XX_MSLUT3				0x63
#define TMC52XX_MSLUT4				0x64
#define TMC52XX_MSLUT5				0x65
#define TMC52XX_MSLUT6				0x66
#define TMC52XX_MSLUT7				0x67
#define TMC52XX_MSLUTSEL			0x68
#define TMC52XX_MSLUTSTART			0x69
#define TMC52XX_MSCNT				0x6A
#define TMC52XX_MSCURACT			0x6B
#define TMC52XX_CHOPCONF			0x6C
#define TMC52XX_COOLCONF			0x6D
#define TMC52XX_DCCTRL				0x6E
#define TMC52XX_DRVSTATUS           0x6F

#define TMC52XX_PWMCONF				0x70
#define TMC52XX_PWM_SCALE     		0x71
#define TMC52XX_PWM_AUTO      		0x72
#define TMC52XX_SG4_THRS      		0x74
#define TMC52XX_SG4_RESULT    		0x75
#define TMC52XX_IND                 0x76

/* === GCONF bit positions (TMC5240) === */
#define TMC52XX_GCONF_FAST_STANDSTILL			BIT(1)
#define TMC52XX_GCONF_EN_PWM_MODE				BIT(2)
#define TMC52XX_GCONF_SHAFT						BIT(4)
#define TMC52XX_GCONF_DIAG0_NINT_STEP			BIT(7)
#define TMC52XX_GCONF_DIAG1_NPOSCOMP_DIR		BIT(8)
#define TMC52XX_GCONF_DIAG0_INT_PUSHPULL		BIT(12)
#define TMC52XX_GCONF_DIAG1_POSCOMP_PUSHPULL	BIT(13)
#define TMC52XX_GCONF_SMALL_HYSTERESIS			BIT(14)
#define TMC52XX_GCONF_STOP_ENABLE				BIT(15)
#define TMC52XX_GCONF_DIRECT_MODE				BIT(16)
/* length_step_pulse is a 4-bit field at bits [20:17] */
#define TMC52XX_GCONF_LENGTH_STEP_PULSE_SHIFT	17
#define TMC52XX_GCONF_LENGTH_STEP_PULSE_MASK	GENMASK(20, 17)
#define TMC52XX_GCONF_LENGTH_STEP_PULSE(n)		(((n) << TMC52XX_GCONF_LENGTH_STEP_PULSE_SHIFT) & TMC52XX_GCONF_LENGTH_STEP_PULSE_MASK)

/* === GSTAT bit positions (TMC5240) === */

#define TMC52XX_GSTAT_RESET						BIT(0)
#define TMC52XX_GSTAT_DRV_ERR					BIT(1)
#define TMC52XX_GSTAT_UV_CP						BIT(2)
#define TMC52XX_GSTAT_REGISTER_RESET			BIT(3)
#define TMC52XX_GSTAT_VM_UVLO					BIT(4)

/* === NODECONF bit positions (TMC5240) === */

#define TMC52XX_NODECONF_NODEADDR_SHIFT			0
#define TMC52XX_NODECONF_NODEADDR_MASK			GENMASK(7, 0)
#define TMC52XX_NODECONF_NODEADDR(n)			(((n) << TMC52XX_NODECONF_NODEADDR_SHIFT) & TMC52XX_NODECONF_NODEADDR_MASK)
#define TMC52XX_NODECONF_SENDDELAY_SHIFT		8
#define TMC52XX_NODECONF_SENDDELAY_MASK			GENMASK(11, 8)
#define TMC52XX_NODECONF_SENDDELAY(n)			(((n) << TMC52XX_NODECONF_SENDDELAY_SHIFT) & TMC52XX_NODECONF_SENDDELAY_MASK)

/* === IOIN bit positions (TMC5240) === */

#define TMC52XX_IOIN_REFL						BIT(0)
#define TMC52XX_IOIN_REFR						BIT(1)
#define TMC52XX_IOIN_ENCB						BIT(2)
#define TMC52XX_IOIN_ENCA						BIT(3)
#define TMC52XX_IOIN_DRV_ENN					BIT(4)
#define TMC52XX_IOIN_ENCN						BIT(5)
#define TMC52XX_IOIN_UART_EN					BIT(6)
#define TMC52XX_IOIN_COMP_A						BIT(8)
#define TMC52XX_IOIN_COMP_B						BIT(9)
#define TMC52XX_IOIN_COMP_A1_A2					BIT(10)
#define TMC52XX_IOIN_COMP_B1_B2					BIT(11)
#define TMC52XX_IOIN_OUTPUT						BIT(12)
#define TMC52XX_IOIN_EXT_RES_DET				BIT(13)
#define TMC52XX_IOIN_EXT_CLK					BIT(14)
#define TMC52XX_IOIN_ADC_ERR					BIT(15)
#define TMC52XX_IOIN_SILICON_RV_SHIFT			16
#define TMC52XX_IOIN_SILICON_RV_MASK			GENMASK(18, 16)
#define TMC52XX_IOIN_SILICON_RV(n)				(((n) << TMC52XX_IOIN_SILICON_RV_SHIFT) & TMC52XX_IOIN_SILICON_RV_MASK)

/* === DRV_CONF bit positions (TMC5240) === */

#define TMC52XX_DRV_CONF_CURRENT_RANGE_SHIFT	0
#define TMC52XX_DRV_CONF_CURRENT_RANGE_MASK		GENMASK(1, 0)
#define TMC52XX_DRV_CONF_CURRENT_RANGE(n)		(((n) << TMC52XX_DRV_CONF_CURRENT_RANGE_SHIFT) & TMC52XX_DRV_CONF_CURRENT_RANGE_MASK)
#define TMC52XX_DRV_CONF_SLOPE_CONTROL_SHIFT	4
#define TMC52XX_DRV_CONF_SLOPE_CONTROL_MASK		GENMASK(5, 4)
#define TMC52XX_DRV_CONF_SLOPE_CONTROL(n)		(((n) << TMC52XX_DRV_CONF_SLOPE_CONTROL_SHIFT) & TMC52XX_DRV_CONF_SLOPE_CONTROL_MASK)

/* === IHOLD_IRUN bit positions (TMC5240) === */

#define TMC52XX_IHOLD_MASK  					GENMASK(4, 0)
#define TMC52XX_IHOLD_SHIFT 					0
#define TMC52XX_IHOLD(n)    					(((n) << TMC52XX_IHOLD_SHIFT) & TMC52XX_IHOLD_MASK)

#define TMC52XX_IRUN_MASK  						GENMASK(12, 8)
#define TMC52XX_IRUN_SHIFT 						8
#define TMC52XX_IRUN(n)    						(((n) << TMC52XX_IRUN_SHIFT) & TMC52XX_IRUN_MASK)

#define TMC52XX_IHOLDDELAY_MASK  				GENMASK(19, 16)
#define TMC52XX_IHOLDDELAY_SHIFT 				16
#define TMC52XX_IHOLDDELAY(n)    				(((n) << TMC52XX_IHOLDDELAY_SHIFT) & TMC52XX_IHOLDDELAY_MASK)

#define TMC52XX_IRUNDELAY_MASK  				GENMASK(27, 24)
#define TMC52XX_IRUNDELAY_SHIFT 				24
#define TMC52XX_IRUNDELAY(n)    				(((n) << TMC52XX_IRUNDELAY_SHIFT) & TMC52XX_IRUNDELAY_MASK)

/* === VDCMIN bit positions (TMC5240) === */

#define TMC52XX_VDCMIN_MASK  					GENMASK(22, 8)
#define TMC52XX_VDCMIN_SHIFT 					8
#define TMC52XX_VDCMIN(n)    					(((n) << TMC52XX_VDCMIN_SHIFT) & TMC52XX_VDCMIN_MASK)

/* === SWMODE bit positions (TMC5240) === */

#define TMC52XX_SWMODE_STOP_L_ENABLE
#define TMC52XX_SWMODE_STOP_R_ENABLE
#define TMC52XX_SWMODE_POL_STOP_L
#define TMC52XX_SWMODE_POL_STOP_R
#define TMC52XX_SWMODE_SWAP_LR
#define TMC52XX_SWMODE_LATCH_L_ACTIVE
#define TMC52XX_SWMODE_LATCH_L_INACTIVE
#define TMC52XX_SWMODE_LATCH_R_ACTIVE
#define TMC52XX_SWMODE_LATCH_R_INACTIVE
#define TMC52XX_SWMODE_EN_LATCH_ENCODER
#define TMC52XX_SWMODE_SG_STOP
#define TMC52XX_SWMODE_EN_SOFTSTOP
#define TMC52XX_SWMODE_EN_VIRTUAL_STOP_L
#define TMC52XX_SWMODE_EN_VIRTUAL_STOP_R
#define TMC52XX_SWMODE_VIRTUAL_STOP_ENC


#define TMC52XX_RAMPSTAT_








#define TMC52XX_CHOPCONF_DRV_ENABLE_MASK GENMASK(3, 0)
#define TMC52XX_CHOPCONF_MRES_MASK       GENMASK(27, 24)
#define TMC52XX_CHOPCONF_MRES_SHIFT      24

#define TMC52XX_RAMPSTAT_INT_MASK  GENMASK(9, 4)
#define TMC52XX_RAMPSTAT_INT_SHIFT 4




// (((n) << _SHIFT) & _MASK)

#endif /* CONFIG_STEPPER_ADI_TMC52XX */

/**
 * @}
 */

#ifdef __cplusplus
}
#endif

#endif /* ZEPHYR_DRIVERS_STEPPER_ADI_TMC_COMMON_ADI_TMC_REG_H_ */
